# Generated by Django 5.2.4 on 2025-12-17 11:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="콘텐츠 ID"
                    ),
                ),
                (
                    "content_type_id",
                    models.CharField(max_length=20, verbose_name="콘텐츠 타입 ID"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="여행지명")),
                ("address", models.CharField(max_length=300, verbose_name="주소")),
                (
                    "area_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="지역코드"
                    ),
                ),
                (
                    "sigungu_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="시군구코드"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="위도",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="경도",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="설명"),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "homepage",
                    models.URLField(blank=True, null=True, verbose_name="홈페이지"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="대표 이미지 URL"
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="썸네일 이미지 URL"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="평점",
                    ),
                ),
                (
                    "review_count",
                    models.IntegerField(default=0, verbose_name="리뷰 수"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="조회수")),
                (
                    "bookmark_count",
                    models.IntegerField(default=0, verbose_name="북마크 수"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 동기화"
                    ),
                ),
            ],
            options={
                "verbose_name": "여행지",
                "verbose_name_plural": "여행지",
                "db_table": "travel_spots",
            },
        ),
        migrations.CreateModel(
            name="TravelSpotCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="카테고리명"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="설명"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="아이콘"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "여행지 카테고리",
                "verbose_name_plural": "여행지 카테고리",
                "db_table": "travel_spot_categories",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="코스 제목")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="설명"),
                ),
                (
                    "total_distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="총 거리(km)",
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="예상 소요시간(분)"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="공개 여부"),
                ),
                (
                    "like_count",
                    models.IntegerField(default=0, verbose_name="좋아요 수"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="조회수")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "여행 코스",
                "verbose_name_plural": "여행 코스",
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="평점",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "accessibility_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="접근성 평점",
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="이미지 URL 목록"
                    ),
                ),
                (
                    "like_count",
                    models.IntegerField(default=0, verbose_name="좋아요 수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "travel_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="api.travelspot",
                        verbose_name="여행지",
                    ),
                ),
            ],
            options={
                "verbose_name": "리뷰",
                "verbose_name_plural": "리뷰",
                "db_table": "reviews",
            },
        ),
        migrations.CreateModel(
            name="CourseSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="순서")),
                ("memo", models.TextField(blank=True, null=True, verbose_name="메모")),
                (
                    "stay_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="체류 시간(분)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_spots",
                        to="api.course",
                        verbose_name="코스",
                    ),
                ),
                (
                    "travel_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_spots",
                        to="api.travelspot",
                        verbose_name="여행지",
                    ),
                ),
            ],
            options={
                "verbose_name": "코스 여행지",
                "verbose_name_plural": "코스 여행지",
                "db_table": "course_spots",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memo", models.TextField(blank=True, null=True, verbose_name="메모")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "travel_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="api.travelspot",
                        verbose_name="여행지",
                    ),
                ),
            ],
            options={
                "verbose_name": "북마크",
                "verbose_name_plural": "북마크",
                "db_table": "bookmarks",
            },
        ),
        migrations.CreateModel(
            name="AccessibilityInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parking",
                    models.BooleanField(default=False, verbose_name="장애인 주차장"),
                ),
                (
                    "route",
                    models.BooleanField(default=False, verbose_name="대중교통 접근"),
                ),
                (
                    "public_transport",
                    models.BooleanField(default=False, verbose_name="무장애 이동경로"),
                ),
                (
                    "restroom",
                    models.BooleanField(default=False, verbose_name="장애인 화장실"),
                ),
                (
                    "wheelchair",
                    models.BooleanField(default=False, verbose_name="휠체어 대여"),
                ),
                ("exit", models.BooleanField(default=False, verbose_name="출입통로")),
                ("elevator", models.BooleanField(default=False, verbose_name="승강기")),
                (
                    "audio_guide",
                    models.BooleanField(default=False, verbose_name="음성안내"),
                ),
                (
                    "parking_info",
                    models.TextField(blank=True, null=True, verbose_name="주차 정보"),
                ),
                (
                    "route_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="이동경로 정보"
                    ),
                ),
                (
                    "restroom_info",
                    models.TextField(blank=True, null=True, verbose_name="화장실 정보"),
                ),
                (
                    "wheelchair_info",
                    models.TextField(blank=True, null=True, verbose_name="휠체어 정보"),
                ),
                (
                    "exit_info",
                    models.TextField(blank=True, null=True, verbose_name="출입구 정보"),
                ),
                (
                    "elevator_info",
                    models.TextField(blank=True, null=True, verbose_name="승강기 정보"),
                ),
                (
                    "braile_block",
                    models.BooleanField(default=False, verbose_name="점자블록"),
                ),
                (
                    "help_dog",
                    models.BooleanField(default=False, verbose_name="안내견 동반"),
                ),
                (
                    "guide_system",
                    models.BooleanField(default=False, verbose_name="유도 안내 설비"),
                ),
                (
                    "stroller",
                    models.BooleanField(default=False, verbose_name="유모차 접근 가능"),
                ),
                (
                    "lactation_room",
                    models.BooleanField(default=False, verbose_name="수유실"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "travel_spot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibility",
                        to="api.travelspot",
                        verbose_name="여행지",
                    ),
                ),
            ],
            options={
                "verbose_name": "무장애 정보",
                "verbose_name_plural": "무장애 정보",
                "db_table": "accessibility_info",
            },
        ),
        migrations.AddField(
            model_name="travelspot",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="travel_spots",
                to="api.travelspotcategory",
                verbose_name="카테고리",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["user", "-created_at"], name="courses_user_id_47cc03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["-like_count"], name="courses_like_co_fcfdc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["travel_spot", "-created_at"], name="reviews_travel__a376ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "-created_at"], name="reviews_user_id_9f7b05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursespot",
            index=models.Index(
                fields=["course", "order"], name="course_spot_course__71a4da_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursespot",
            unique_together={("course", "travel_spot")},
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "-created_at"], name="bookmarks_user_id_6c0ac9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together={("user", "travel_spot")},
        ),
        migrations.AddIndex(
            model_name="travelspot",
            index=models.Index(
                fields=["content_id"], name="travel_spot_content_0e9b61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="travelspot",
            index=models.Index(
                fields=["area_code", "sigungu_code"],
                name="travel_spot_area_co_90d4ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="travelspot",
            index=models.Index(
                fields=["-created_at"], name="travel_spot_created_ca7ab4_idx"
            ),
        ),
    ]
