# Generated by Django 5.2.4 on 2025-12-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelspot",
            name="tel",
            field=models.TextField(blank=True, null=True, verbose_name="전화번호"),
        ),
    ]
