# Generated by Django 5.2.4 on 2025-12-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_travelspot_tel"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibilityinfo",
            name="audio_guide_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="오디오 가이드 정보"
            ),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="auditorium",
            field=models.BooleanField(default=False, verbose_name="관람석"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="auditorium_info",
            field=models.TextField(blank=True, null=True, verbose_name="관람석 정보"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="baby_spare_chair",
            field=models.BooleanField(default=False, verbose_name="유아용 보조의자"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="baby_spare_chair_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="유아용 보조의자 정보"
            ),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="big_print",
            field=models.BooleanField(default=False, verbose_name="큰 활자 홍보물"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="big_print_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="큰 활자 홍보물 정보"
            ),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="blind_handicap_etc",
            field=models.TextField(
                blank=True, null=True, verbose_name="시각장애 기타 상세"
            ),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="braile_block_info",
            field=models.TextField(blank=True, null=True, verbose_name="점자블록 정보"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="braile_promotion",
            field=models.BooleanField(default=False, verbose_name="점자 홍보물"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="braile_promotion_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="점자 홍보물 정보"
            ),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="guide_human",
            field=models.BooleanField(default=False, verbose_name="안내요원"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="guide_human_info",
            field=models.TextField(blank=True, null=True, verbose_name="안내요원 정보"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="guide_system_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="유도 안내 설비 정보"
            ),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="handicap_etc",
            field=models.TextField(
                blank=True, null=True, verbose_name="지체장애 기타 상세"
            ),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="hearing_handicap_etc",
            field=models.TextField(
                blank=True, null=True, verbose_name="청각장애 기타 상세"
            ),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="hearing_room",
            field=models.BooleanField(default=False, verbose_name="청각장애 객실"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="hearing_room_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="청각장애 객실 정보"
            ),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="help_dog_info",
            field=models.TextField(blank=True, null=True, verbose_name="보조견 정보"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="infants_family_etc",
            field=models.TextField(
                blank=True, null=True, verbose_name="영유아가족 기타 상세"
            ),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="lactation_room_info",
            field=models.TextField(blank=True, null=True, verbose_name="수유실 정보"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="promotion",
            field=models.BooleanField(default=False, verbose_name="홍보물"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="promotion_info",
            field=models.TextField(blank=True, null=True, verbose_name="홍보물 정보"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="public_transport_info",
            field=models.TextField(blank=True, null=True, verbose_name="대중교통 정보"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="room",
            field=models.BooleanField(default=False, verbose_name="객실"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="room_info",
            field=models.TextField(blank=True, null=True, verbose_name="객실 정보"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="sign_guide",
            field=models.BooleanField(default=False, verbose_name="수화 안내"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="sign_guide_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="수화 안내 정보"
            ),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="stroller_info",
            field=models.TextField(blank=True, null=True, verbose_name="유모차 정보"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="ticket_office",
            field=models.BooleanField(default=False, verbose_name="매표소"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="ticket_office_info",
            field=models.TextField(blank=True, null=True, verbose_name="매표소 정보"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="video_guide",
            field=models.BooleanField(default=False, verbose_name="자막 비디오 가이드"),
        ),
        migrations.AddField(
            model_name="accessibilityinfo",
            name="video_guide_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="자막 비디오 가이드 정보"
            ),
        ),
        migrations.AlterField(
            model_name="accessibilityinfo",
            name="audio_guide",
            field=models.BooleanField(default=False, verbose_name="오디오 가이드"),
        ),
        migrations.AlterField(
            model_name="accessibilityinfo",
            name="elevator",
            field=models.BooleanField(default=False, verbose_name="엘리베이터"),
        ),
        migrations.AlterField(
            model_name="accessibilityinfo",
            name="elevator_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="엘리베이터 정보"
            ),
        ),
        migrations.AlterField(
            model_name="accessibilityinfo",
            name="exit_info",
            field=models.TextField(blank=True, null=True, verbose_name="출입통로 정보"),
        ),
        migrations.AlterField(
            model_name="accessibilityinfo",
            name="help_dog",
            field=models.BooleanField(default=False, verbose_name="보조견 동반"),
        ),
        migrations.AlterField(
            model_name="accessibilityinfo",
            name="public_transport",
            field=models.BooleanField(default=False, verbose_name="대중교통"),
        ),
        migrations.AlterField(
            model_name="accessibilityinfo",
            name="route",
            field=models.BooleanField(default=False, verbose_name="접근로"),
        ),
        migrations.AlterField(
            model_name="accessibilityinfo",
            name="route_info",
            field=models.TextField(blank=True, null=True, verbose_name="접근로 정보"),
        ),
        migrations.AlterField(
            model_name="accessibilityinfo",
            name="stroller",
            field=models.BooleanField(default=False, verbose_name="유모차"),
        ),
        migrations.AlterField(
            model_name="accessibilityinfo",
            name="wheelchair",
            field=models.BooleanField(default=False, verbose_name="휠체어"),
        ),
    ]
