# Generated by Django 5.2.4 on 2025-12-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_accessibilityinfo_audio_guide_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='audio_guide_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='auditorium',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='auditorium_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='baby_spare_chair',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='baby_spare_chair_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='big_print',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='big_print_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='blind_handicap_etc',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='braile_block_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='braile_promotion',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='braile_promotion_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='guide_human',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='guide_human_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='guide_system_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='handicap_etc',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='hearing_handicap_etc',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='hearing_room',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='hearing_room_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='help_dog_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='infants_family_etc',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='lactation_room_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='promotion_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='public_transport_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='room',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='room_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='sign_guide',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='sign_guide_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='stroller_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='ticket_office',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='ticket_office_info',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='video_guide',
        ),
        migrations.RemoveField(
            model_name='accessibilityinfo',
            name='video_guide_info',
        ),
        migrations.AddField(
            model_name='travelspot',
            name='addr1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='addr2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='상세주소'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='cat1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='대분류'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='cat2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='중분류'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='cat3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='소분류'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='cpyrht_div_cd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='저작권 유형'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='created_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='API 등록일'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='mlevel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Map Level'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='modified_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='API 수정일'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='개요'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='tel_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='전화번호명'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='우편번호'),
        ),
        migrations.AlterField(
            model_name='accessibilityinfo',
            name='audio_guide',
            field=models.BooleanField(default=False, verbose_name='음성안내'),
        ),
        migrations.AlterField(
            model_name='accessibilityinfo',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='승강기'),
        ),
        migrations.AlterField(
            model_name='accessibilityinfo',
            name='elevator_info',
            field=models.TextField(blank=True, null=True, verbose_name='승강기 정보'),
        ),
        migrations.AlterField(
            model_name='accessibilityinfo',
            name='exit_info',
            field=models.TextField(blank=True, null=True, verbose_name='출입구 정보'),
        ),
        migrations.AlterField(
            model_name='accessibilityinfo',
            name='help_dog',
            field=models.BooleanField(default=False, verbose_name='안내견 동반'),
        ),
        migrations.AlterField(
            model_name='accessibilityinfo',
            name='public_transport',
            field=models.BooleanField(default=False, verbose_name='무장애 이동경로'),
        ),
        migrations.AlterField(
            model_name='accessibilityinfo',
            name='route',
            field=models.BooleanField(default=False, verbose_name='대중교통 접근'),
        ),
        migrations.AlterField(
            model_name='accessibilityinfo',
            name='route_info',
            field=models.TextField(blank=True, null=True, verbose_name='이동경로 정보'),
        ),
        migrations.AlterField(
            model_name='accessibilityinfo',
            name='stroller',
            field=models.BooleanField(default=False, verbose_name='유모차 접근 가능'),
        ),
        migrations.AlterField(
            model_name='accessibilityinfo',
            name='wheelchair',
            field=models.BooleanField(default=False, verbose_name='휠체어 대여'),
        ),
        migrations.AlterField(
            model_name='travelspot',
            name='homepage',
            field=models.TextField(blank=True, null=True, verbose_name='홈페이지'),
        ),
    ]
