# Generated by Django 5.2.4 on 2025-12-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_accessibilityinfo_audio_guide_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilityinfo',
            name='hearing_room',
            field=models.BooleanField(default=False, verbose_name='청각장애 객실'),
        ),
        migrations.AddField(
            model_name='accessibilityinfo',
            name='sign_guide',
            field=models.BooleanField(default=False, verbose_name='수화 안내'),
        ),
        migrations.AddField(
            model_name='accessibilityinfo',
            name='video_guide',
            field=models.BooleanField(default=False, verbose_name='자막 비디오 가이드'),
        ),
    ]
