# Generated by Django 5.2.4 on 2025-12-23 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_accessibilityinfo_hearing_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.course', verbose_name='코스')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.coursecomment', verbose_name='부모 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comments', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '코스 댓글',
                'verbose_name_plural': '코스 댓글',
                'db_table': 'course_comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', '-created_at'], name='course_comm_course__729d25_idx'), models.Index(fields=['user', '-created_at'], name='course_comm_user_id_1290a1_idx')],
            },
        ),
    ]
