# Generated by Django 5.2.4 on 2025-12-23 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_coursecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.course', verbose_name='코스')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '코스 좋아요',
                'verbose_name_plural': '코스 좋아요',
                'db_table': 'course_likes',
                'indexes': [models.Index(fields=['user', '-created_at'], name='course_like_user_id_718287_idx'), models.Index(fields=['course', '-created_at'], name='course_like_course__5ead5e_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
