# Generated by Django 5.2.4 on 2025-12-24 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_courselike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelspot',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='평점'),
        ),
    ]
