# Generated by Django 5.2.4 on 2025-12-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth",
            field=models.DateField(blank=True, null=True, verbose_name="생년월일"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "남자"), ("F", "여자")],
                max_length=1,
                null=True,
                verbose_name="성별",
            ),
        ),
    ]
